-- seed.sql — paste into the Supabase SQL editor to load/refresh the events.
-- Safe to run repeatedly: it upserts on id.

insert into public.events (id, layer, track, title, date, "endDate", "start", "end", repeat, until, "skipBreaks", "where", host, link, notes, committee, unconfirmed, "isBreak") values
  ('a-f-start', 'academic', NULL, 'Fall term begins', '2026-08-24', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('pf-orient1', 'event', 'hm', 'Orientation', '2026-08-29', NULL, '', '', 'none', NULL, true, '', '', '', 'Annual orientation, TARP IV.A.2. At least two members of the Branch Committee take part.', '', false, NULL),
  ('s-birt', 'event', 'dl', 'BIRT cutoff — 24h before Housemeeting', '2026-08-26', NULL, '20:00', '', 'weekly', '2027-05-06', true, '', '', '', 'A BIRT must hit the listserv 24h before the meeting that considers it.', '', false, NULL),
  ('s-hm', 'event', 'hm', 'Housemeeting', '2026-08-27', NULL, '20:00', '22:00', 'weekly', '2027-05-07', true, 'Dutch', '', '', 'Weekly House meeting. Runs until it finishes, usually around 10.', '', false, NULL),
  ('pf-orient2', 'event', 'hm', 'Orientation Pt. 2 — trainings', '2026-09-05', NULL, '', '', 'none', NULL, true, '', '', '', 'Harassment & conflict-resolution training, TARP IV.A.1(c)v. Due within the first two months.', '', false, NULL),
  ('a-labor', 'academic', NULL, 'Labor Day — no classes', '2026-09-07', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, true),
  ('a-add-f', 'academic', NULL, 'Last day to add (regular session)', '2026-09-08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('pf-chef1', 'event', 'chef', 'CHEF 1 — review the application questions', '2026-09-17', NULL, '', '', 'none', NULL, true, '', '', '', 'PreferCom. This is the CHEF that must land before any application reading begins.', '', false, NULL),
  ('nh-1', 'event', 'cm', 'Nunnian / Hill', '2026-09-18', NULL, '', '', 'none', NULL, true, '', '', '', 'Inter-Nunnian Committee.', '', false, NULL),
  ('s-prefercom', 'event', 'cm', 'PreferCom meeting', '2026-09-20', NULL, '11:45', '12:45', 'weekly', '2027-05-09', true, '', '', '', 'The one committee time that is confirmed. Everything else on the Committees track is a guess until its chair fixes it.', 'prefercom', false, NULL),
  ('pf-draft', 'event', 'pref', 'Send draft application to the office', '2026-09-21', NULL, '', '', 'none', NULL, true, '', '', '', 'PreferCom.', '', false, NULL),
  ('s-miscops-prelim', 'event', 'dl', 'Preliminary MiscOps budget to CBC', '2026-09-21', NULL, '', '', 'none', NULL, true, '', '', '', 'Due within a month of move-in. Anchor to when the House opened.', '', true, NULL),
  ('s-se', 'event', 'dl', 'Standards & Expectations document to CBC', '2026-09-21', NULL, '', '', 'none', NULL, true, '', '', '', 'Standards & Expectations doc to CBC within the first month; two-thirds House vote.', '', true, NULL),
  ('ps-daeden', 'event', 'forum', 'PubSpeak: Daeden — Every Drug in the World + Medical AMA', '2026-09-27', NULL, '17:00', '18:00', 'none', NULL, true, '', '', '', 'Topic: Every Drug in the World + Medical AMA', '', false, NULL),
  ('nh-2', 'event', 'cm', 'Nunnian / Hill', '2026-10-01', NULL, '', '', 'none', NULL, true, '', '', '', 'Inter-Nunnian Committee.', '', false, NULL),
  ('pf-chef2', 'event', 'chef', 'CHEF 2 — mock application discussion', '2026-10-01', NULL, '', '', 'none', NULL, true, '', '', '', 'PreferCom.', '', false, NULL),
  ('pf-release', 'event', 'pref', 'Application released', '2026-10-01', NULL, '', '', 'none', NULL, true, '', '', '', 'PreferCom. TARP IV.A.4(a): no application submitted after the deadline is considered.', '', false, NULL),
  ('ps-andy', 'event', 'forum', 'PubSpeak: Andy Ramnauth', '2026-10-03', NULL, '13:00', '14:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('ps-vaughn', 'event', 'forum', 'PubSpeak: Vaughn', '2026-10-03', NULL, '17:00', '18:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('ps-urna', 'event', 'forum', 'PubSpeak: Urna — Tradwife Cosplay', '2026-10-04', NULL, '17:00', '18:00', 'none', NULL, true, '', '', '', 'Topic: Tradwife Cosplay', '', false, NULL),
  ('pf-oh1', 'event', 'pref', 'Open House 1', '2026-10-07', NULL, '', '', 'none', NULL, true, '', 'house', '', 'PreferCom organizes; tell the kitchen staff the date. CommsCom spreads the word.', '', false, NULL),
  ('a-7w1-end-f', 'academic', NULL, 'Last day of instruction, 7-week 1', '2026-10-09', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('a-fallbreak', 'academic', NULL, 'Fall Break', '2026-10-10', '2026-10-13', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, true),
  ('a-7w2-f', 'academic', NULL, '7-week 2 begins', '2026-10-14', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('nh-3', 'event', 'cm', 'Nunnian / Hill', '2026-10-15', NULL, '', '', 'none', NULL, true, '', '', '', 'Inter-Nunnian Committee.', '', false, NULL),
  ('pf-chef3', 'event', 'chef', 'CHEF 3 — interview sheet revamp', '2026-10-15', NULL, '', '', 'none', NULL, true, '', '', '', 'PreferCom.', '', false, NULL),
  ('ps-riya', 'event', 'forum', 'PubSpeak: Riya', '2026-10-17', NULL, '13:00', '14:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('ps-tahm', 'event', 'forum', 'PubSpeak: Tahm', '2026-10-18', NULL, '13:00', '14:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('a-drop-f', 'academic', NULL, 'Last day to drop or change grading basis', '2026-10-19', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('pf-guest', 'event', 'forum', 'Guest Speaker', '2026-10-20', NULL, '', '', 'none', NULL, true, '', '', '', 'On the preferment calendar with no name attached. AcAff keeps a shortlist of twelve candidates — see the tray.', '', true, NULL),
  ('s-edplan', 'event', 'dl', 'Year-long educational plan to CBC', '2026-10-21', NULL, '', '', 'none', NULL, true, '', '', '', 'Year-long educational plan to CBC within two months; one event per semester.', '', true, NULL),
  ('s-tos-statement', 'event', 'dl', 'Terms of Scholarship statement to CBC', '2026-10-21', NULL, '', '', 'none', NULL, true, '', '', '', 'Terms of Scholarship statement to CBC within the first two months.', '', true, NULL),
  ('s-training', 'event', 'dl', 'Orientation training complete', '2026-10-21', NULL, '', '', 'none', NULL, true, '', '', '', 'Harassment & conflict-resolution training done within the first two months.', '', true, NULL),
  ('pf-oh2', 'event', 'pref', 'Open House 2', '2026-10-22', NULL, '', '', 'none', NULL, true, '', 'house', '', 'PreferCom.', '', false, NULL),
  ('pf-soccom', 'event', 'soc', 'SocCom event (e.g. Spades Night)', '2026-10-23', NULL, '', '', 'none', NULL, true, '', 'house', '', 'On the preferment calendar as recruitment-adjacent. SocialCom runs it.', '', false, NULL),
  ('ps-goutham', 'event', 'forum', 'PubSpeak: Goutham', '2026-10-24', NULL, '13:00', '14:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('ps-elliot', 'event', 'forum', 'PubSpeak: Elliot', '2026-10-24', NULL, '17:00', '18:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('nh-4', 'event', 'cm', 'Nunnian / Hill', '2026-10-29', NULL, '', '', 'none', NULL, true, '', '', '', 'Inter-Nunnian Committee.', '', false, NULL),
  ('pf-chef4', 'event', 'chef', 'CHEF 4 — preferment meeting practice', '2026-10-29', NULL, '', '', 'none', NULL, true, '', '', '', 'PreferCom. Second of the two preferment CHEFs the committee owes this semester.', '', false, NULL),
  ('nh-5', 'event', 'cm', 'Nunnian / Hill', '2026-10-31', NULL, '', '', 'none', NULL, true, '', '', '', 'Inter-Nunnian Committee.', '', false, NULL),
  ('pf-deadline', 'event', 'pref', 'Application deadline', '2026-10-31', NULL, '', '', 'none', NULL, true, '', '', '', 'Falls in the Saturday column of the week of Oct 26 on the PreferCom sheet, so Oct 31. Worth confirming it is not Nov 1.', '', true, NULL),
  ('s-halloween', 'event', 'soc', 'Halloween party', '2026-10-31', NULL, '', '', 'none', NULL, true, '', 'house', '', 'SocialCom event. Over ten outside guests needs legislation two weeks out.', '', true, NULL),
  ('s-miscops-final', 'event', 'dl', 'Final MiscOps budget due to CBC', '2026-10-31', NULL, '', '', 'none', NULL, true, '', '', '', 'Final MiscOps budget to CBC by Oct 31.', '', false, NULL),
  ('ps-sophie', 'event', 'forum', 'PubSpeak: Sophie', '2026-11-01', NULL, '13:00', '14:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('pf-reading', 'event', 'pref', 'Reading period', '2026-11-02', '2026-11-06', '', '', 'none', NULL, true, '', '', '', 'Reading period. Capped at 80 readings per Branchmember per year.', '', false, NULL),
  ('nh-6', 'event', 'cm', 'Nunnian / Hill', '2026-11-07', NULL, '', '', 'none', NULL, true, '', '', '', 'Inter-Nunnian Committee.', '', false, NULL),
  ('pf-cut', 'event', 'pref', 'Cut meeting', '2026-11-07', NULL, '', '', 'none', NULL, true, '', '', '', 'Mandatory Preferment Meeting (Bylaws V.3).', '', false, NULL),
  ('pf-interview', 'event', 'pref', 'Interview period', '2026-11-09', '2026-11-13', '', '', 'none', NULL, true, '', '', '', 'Banner across the week of Nov 9 on the sheet. Tell RGC if anyone is staying over.', '', false, NULL),
  ('a-drop-7w2', 'academic', NULL, 'Last day to drop, 7-week 2', '2026-11-11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('nh-7', 'event', 'cm', 'Nunnian / Hill', '2026-11-14', NULL, '', '', 'none', NULL, true, '', '', '', 'Inter-Nunnian Committee.', '', false, NULL),
  ('pf-prefmtg', 'event', 'pref', 'Preferment meeting', '2026-11-14', NULL, '', '', 'none', NULL, true, '', '', '', 'Mandatory Preferment Meeting (Bylaws V.3).', '', false, NULL),
  ('a-thanks', 'academic', NULL, 'Thanksgiving Break', '2026-11-25', '2026-11-29', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, true),
  ('a-7w2-end', 'academic', NULL, 'Last day of instruction, 7-week 2', '2026-12-04', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('a-last-f', 'academic', NULL, 'Last day of instruction', '2026-12-07', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('s-reimb-close', 'event', 'dl', 'Last day to submit fall reimbursements', '2026-12-07', NULL, '', '', 'none', NULL, true, '', '', '', 'Last day to submit fall reimbursements. Nothing after the last day of class.', '', false, NULL),
  ('a-study-f', 'academic', NULL, 'Study days', '2026-12-08', '2026-12-10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, true),
  ('a-finals-f', 'academic', NULL, 'Final exams', '2026-12-11', '2026-12-19', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, true),
  ('a-winterrecess', 'academic', NULL, 'Winter recess', '2026-12-20', '2027-01-24', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, true),
  ('s-vacate-f', 'event', 'kitchen', 'Rooms vacated (2 days after last final)', '2026-12-21', NULL, '', '', 'none', NULL, true, '', '', '', 'TARP IV.A.1(d), unless the Head of Staff or MPM approves a longer stay.', '', false, NULL),
  ('a-winterterm', 'academic', NULL, 'Winter term starts', '2026-12-28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('a-winter-inst', 'academic', NULL, 'Winter session instruction begins', '2027-01-04', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('a-winter-end', 'academic', NULL, 'Winter session ends', '2027-01-23', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('a-s-start', 'academic', NULL, 'Spring term begins', '2027-01-25', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('sp-winterseminar', 'event', 'forum', 'Potential winter seminar', '2027-01-30', NULL, '', '', 'none', NULL, true, '', '', '', 'Marked POTENTIAL on the AcAff sheet.', '', true, NULL),
  ('ps-rejoice', 'event', 'forum', 'PubSpeak: Rejoice', '2027-02-06', NULL, '17:00', '18:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('ps-himani', 'event', 'forum', 'PubSpeak: Himani', '2027-02-07', NULL, '13:00', '14:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('a-add-s', 'academic', NULL, 'Last day to add (regular session)', '2027-02-08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('a-febbreak', 'academic', NULL, 'February Break', '2027-02-13', '2027-02-16', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, true),
  ('sp-ceup-chef1', 'event', 'chef', 'CEU / Perkins CHEF #1', '2027-02-18', NULL, '', '', 'none', NULL, true, '', '', '', 'First CHEF of the spring scholarship cycle.', '', false, NULL),
  ('ps-farah', 'event', 'forum', 'PubSpeak: Farah', '2027-02-21', NULL, '13:00', '14:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('ps-adam', 'event', 'forum', 'PubSpeak: Adam', '2027-02-21', NULL, '17:00', '18:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-ceup-open', 'event', 'pref', 'CEU / Perkins application opens', '2027-02-22', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('ps-raaz', 'event', 'forum', 'PubSpeak: Raaz', '2027-02-28', NULL, '13:00', '14:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-ceu-webinar', 'event', 'pref', 'CEU webinar (tentative)', '2027-03-01', NULL, '', '', 'none', NULL, true, '', '', '', 'Marked TENT on the sheet.', '', true, NULL),
  ('sp-ff-chef1', 'event', 'chef', 'Faculty Fellow CHEF #1', '2027-03-04', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-perkins-webinar', 'event', 'pref', 'Perkins webinar (tentative)', '2027-03-06', NULL, '', '', 'none', NULL, true, '', '', '', 'Marked TENT on the sheet.', '', true, NULL),
  ('sp-ff-open', 'event', 'pref', 'Faculty Fellow application opens', '2027-03-08', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('ps-mariah', 'event', 'forum', 'PubSpeak: Mariah', '2027-03-14', NULL, '17:00', '18:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('a-7w1-end-s', 'academic', NULL, 'Last day of instruction, 7-week 1', '2027-03-16', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('a-7w2-s', 'academic', NULL, '7-week 2 begins', '2027-03-17', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('sp-perkins-close', 'event', 'pref', 'Perkins application closes', '2027-03-21', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-perkins-reads', 'event', 'pref', 'Perkins application reads', '2027-03-22', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-perkins-cut', 'event', 'pref', 'Perkins cut meeting', '2027-03-25', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('a-springbreak', 'academic', NULL, 'Spring Break', '2027-03-27', '2027-04-04', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, true),
  ('sp-perkins-int', 'event', 'pref', 'Perkins interviews', '2027-04-05', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-ff-chef2', 'event', 'chef', 'Faculty Fellow CHEF #2', '2027-04-08', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-perkins-pref', 'event', 'pref', 'Perkins preferment meeting', '2027-04-10', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('ps-braden', 'event', 'forum', 'PubSpeak: Braden Stillwell', '2027-04-17', NULL, '13:00', '14:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-ceu-close', 'event', 'pref', 'CEU application closes', '2027-04-18', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-ff-close', 'event', 'pref', 'Faculty Fellow application closes', '2027-04-19', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-ceu-reads', 'event', 'pref', 'CEU application reads', '2027-04-20', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-ff-reads', 'event', 'pref', 'Faculty Fellow application reads', '2027-04-20', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-ceu-cut', 'event', 'pref', 'CEU cut meeting', '2027-04-22', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-ff-cut', 'event', 'pref', 'Faculty Fellow cut meeting', '2027-04-22', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('ps-gemmechu', 'event', 'forum', 'PubSpeak: Gemmechu', '2027-04-24', NULL, '17:00', '18:00', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-ceu-int', 'event', 'pref', 'CEU interviews', '2027-04-26', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-ff-int', 'event', 'pref', 'Faculty Fellow interviews', '2027-04-26', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('sp-ceuff-pref', 'event', 'pref', 'CEU / Faculty Fellow preferment meeting', '2027-04-29', NULL, '', '', 'none', NULL, true, '', '', '', '', '', false, NULL),
  ('a-last-s', 'academic', NULL, 'Last day of instruction', '2027-05-11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, false),
  ('a-study-s', 'academic', NULL, 'Study days', '2027-05-12', '2027-05-14', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, true),
  ('a-finals-s', 'academic', NULL, 'Final exams', '2027-05-15', '2027-05-22', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, true),
  ('s-vacate-s', 'event', 'kitchen', 'Rooms vacated (2 days after last final)', '2027-05-24', NULL, '', '', 'none', NULL, true, '', '', '', 'TARP IV.A.1(d).', '', false, NULL),
  ('a-commence', 'academic', NULL, 'Commencement weekend', '2027-05-28', '2027-05-30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, true),
  ('t-acaff', 'event', 'cm', 'AcAff meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'acaff', false, NULL),
  ('t-adcom', 'event', 'cm', 'AdCom meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'adcom', false, NULL),
  ('t-atkins', 'event', 'pref', 'Atkins Scholar cycle — no dates set', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'Atkins Scholar cycle is listed but no dates are set yet — the gap in the spring calendar.', '', false, NULL),
  ('t-blacktie', 'event', 'soc', 'Black tie dinner', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'SocialCom large-scale event.', '', false, NULL),
  ('t-cbc', 'event', 'cm', 'CBC Liaison meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'cbc', false, NULL),
  ('t-cbcvisit', 'event', 'hm', 'CBC Orientation & visit', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'The CBC Liaison (Mariah) coordinates Branch Committee orientation and visits.', '', false, NULL),
  ('t-chairs', 'event', 'cm', 'Chairs meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'chairs', false, NULL),
  ('t-cleaning', 'event', 'kitchen', 'Cleaning shift & lock-up schedule — HAG', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'HAG maintains the cleaning shift and door lock-up schedules (Adam S, Sophia D., Riya, Elliot).', '', false, NULL),
  ('t-commscom', 'event', 'cm', 'CommsCom meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'commscom', false, NULL),
  ('t-crwg', 'event', 'cm', 'CRWG Liaison meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'crwg', false, NULL),
  ('t-custodianship', 'event', 'cm', 'Custodianship meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'custodianship', false, NULL),
  ('t-deepsprings', 'event', 'world', 'Deep Springs exchange', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'Tahm coordinates.', '', false, NULL),
  ('t-ds', 'event', 'cm', 'Deep Springs Liaison meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'ds', false, NULL),
  ('t-ec', 'event', 'cm', 'ECs meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'ec', false, NULL),
  ('t-facdinner', 'event', 'forum', 'Faculty Dinner', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'AcAff. Tell the kitchen staff the date as soon as it is set.', '', false, NULL),
  ('t-finseminar', 'event', 'dl', 'Treasurers’ financial seminar', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'Treasurers'' financial seminar. Mandatory for all Branchmembers.', '', false, NULL),
  ('t-guestlist', 'event', 'forum', 'Guest speaker shortlist — AcAff', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'AcAff shortlist, none booked yet: Nora Prior, Seema Golastaneh, Jill Collen Jefferson, Francis Fukuyama, Mildred Warner, Jitendra Malik, Stephen Macedo, Stef Funk, Lucinda Ramberg, Lorenzo Alvisi, Emily Lim Rogers, Naeem Inayatullah.', '', false, NULL),
  ('t-guests', 'event', 'kitchen', 'Guest arrivals — RGC calendar', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'RGC (Adam S, Brume, Goutham) keeps the guest calendar. A guest room used more than a week needs a BIRT.', '', false, NULL),
  ('t-hag', 'event', 'cm', 'HAG meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'hag', false, NULL),
  ('t-headshots', 'event', 'dl', 'Headshots & bios due — CommsCom', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'Headshots & bios due for the website (CommsCom). Set a date to move it to the grid.', '', false, NULL),
  ('t-health', 'event', 'cm', 'Health Liaison meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'health', false, NULL),
  ('t-housephoto', 'event', 'soc', 'House photo & swag', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'SocialCom designs and purchases House memorabilia.', '', false, NULL),
  ('t-kitchenrota', 'event', 'kitchen', 'Kitchen shift rotation — ECs to publish', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'ECs publish the kitchen shift rotation. Each shift becomes a repeating entry.', '', false, NULL),
  ('t-leftovers', 'event', 'kitchen', 'Leftover distribution', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'ECs facilitate, consulting the House and the staff.', '', false, NULL),
  ('t-mbta', 'event', 'cm', 'Michigan Branch Liaison meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'mbta', false, NULL),
  ('t-michigan', 'event', 'world', 'Michigan exchange', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'Yearly Michigan exchange. A selection of the House is going this year.', '', false, NULL),
  ('t-midsem-f', 'event', 'hm', 'Mid-semester evaluations — fall', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'Bylaws VI.1: an interview with a member of AdCom, on a schedule AdCom sets. AdCom: Urna, Braden, Sophie, Farah.', '', false, NULL),
  ('t-midsem-s', 'event', 'hm', 'Mid-semester evaluations — spring', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'Bylaws VI.1.', '', false, NULL),
  ('t-pubspeak-gap', 'event', 'forum', 'PubSpeaks with no slot yet', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'Some Branchmembers still owe a PubSpeak slot this year.', '', false, NULL),
  ('t-rgc', 'event', 'cm', 'RGC meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'rgc', false, NULL),
  ('t-scholvotes', 'event', 'hm', 'End-of-semester scholarship & TA membership votes', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'End-of-semester scholarship & TA membership votes (Bylaws VI.3).', '', false, NULL),
  ('t-secretary', 'event', 'cm', 'Secretary, Admin & Library meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'secretary', false, NULL),
  ('t-socform', 'event', 'dl', 'Socials interest form due — SocialCom', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'SocialCom (Mariah, Simran, Gemmechu, Raaz) collecting what people actually want. Set a close date.', '', false, NULL),
  ('t-socialcom', 'event', 'cm', 'SocialCom meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'socialcom', false, NULL),
  ('t-sparc', 'event', 'pref', 'SPARC Orientation', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'TASSCom (Elliot) coordinates.', '', false, NULL),
  ('t-tass-read', 'event', 'pref', 'TASS application readings', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'TASSCom oversees Summer Program application readings.', '', false, NULL),
  ('t-tasscom', 'event', 'cm', 'TASSCom meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'tasscom', false, NULL),
  ('t-tawp', 'event', 'forum', 'TAWP — Telluride Association Winter Program', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'AcAff organizes. Winter.', '', false, NULL),
  ('t-treasury', 'event', 'cm', 'Treasurers meeting', NULL, NULL, '', '', 'none', NULL, true, '', '', '', '', 'treasury', false, NULL),
  ('t-winterformal', 'event', 'soc', 'Winter Formal', NULL, NULL, '', '', 'none', NULL, true, '', '', '', 'Organized by the ECs (Raaziq, Goutham).', '', false, NULL)
on conflict (id) do update set
  layer = excluded.layer,
  track = excluded.track,
  title = excluded.title,
  date = excluded.date,
  "endDate" = excluded."endDate",
  "start" = excluded."start",
  "end" = excluded."end",
  repeat = excluded.repeat,
  until = excluded.until,
  "skipBreaks" = excluded."skipBreaks",
  "where" = excluded."where",
  host = excluded.host,
  link = excluded.link,
  notes = excluded.notes,
  committee = excluded.committee,
  unconfirmed = excluded.unconfirmed,
  "isBreak" = excluded."isBreak",
  updated_at = now();
